name: mamba
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.14=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_1
  - conda-pack=0.7.1=py310h06a4308_0
  - debugpy=1.8.11=py310hf71b8c6_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.0=py310ha75aee5_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.18.0=pyhd8ed1ab_1
  - python=3.10.15=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h71f11fc_3
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py310ha75aee5_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - aiosignal==1.3.1
      - argparse==1.4.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - black==24.10.0
      - blinker==1.9.0
      - brax==0.10.3
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.0
      - chex==0.1.90
      - click==8.1.7
      - cloudpickle==3.1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==0.29.37
      - deepdiff==8.0.1
      - distlib==0.3.9
      - distrax==0.1.5
      - dm-env==1.6
      - dm-env-rpc==1.1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - elements==3.19.1
      - ema-pytorch==0.7.7
      - enum34==1.1.10
      - etils==1.13.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - filelock==3.16.1
      - flake8==7.1.1
      - flake8-bugbear==24.10.31
      - flask==3.1.2
      - flask-cors==6.0.1
      - flax==0.10.4
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - future==1.0.0
      - gast==0.7.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.5.1
      - google-api-core==2.24.1
      - google-auth==2.38.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==3.0.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.65.0
      - grpcio==1.67.1
      - gym==0.21.0
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - gymnax==0.0.9
      - h5py==3.12.1
      - hf-xet==1.1.2
      - huggingface-hub==0.32.2
      - humanize==4.14.0
      - identify==2.6.2
      - idna==3.10
      - imageio==2.36.0
      - immutabledict==4.2.0
      - importlib-metadata==4.13.0
      - importlib-resources==6.5.2
      - ipdb==0.13.13
      - ipython==8.29.0
      - itsdangerous==2.2.0
      - jax==0.4.31
      - jax-cuda12-pjrt==0.4.31
      - jax-cuda12-plugin==0.4.31
      - jaxlib==0.4.31
      - jaxmarl==0.1.0
      - jaxopt==0.8.5
      - jinja2==3.1.6
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - markdown==3.7
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - ml-collections==1.1.0
      - ml-dtypes==0.5.4
      - mock==5.1.0
      - mpmath==1.3.0
      - mpyq==0.2.5
      - msgpack==1.1.0
      - mujoco==3.1.3
      - mujoco-mjx==3.1.3
      - mujoco-py==2.1.2.14
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - nodeenv==1.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.17.0.29
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.2
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optax==0.2.5
      - orbax-checkpoint==0.6.4
      - orderly-set==5.2.2
      - pandas==2.3.3
      - patchelf==0.17.2.1
      - pathspec==0.12.1
      - pettingzoo==1.22.2
      - pillow==11.0.0
      - pip==21.0
      - portpicker==1.6.0
      - pre-commit==4.0.1
      - proto-plus==1.26.0
      - protobuf==3.20.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pyflakes==3.2.0
      - pygame==2.1.2
      - pyglet==1.5.0
      - pymunk==6.2.1
      - pyopengl==3.1.7
      - pyparsing==3.2.0
      - pysc2==4.0.0
      - pytinyrenderer==0.0.14
      - pytz==2025.2
      - pyyaml==6.0.2
      - ray==2.38.0
      - referencing==0.35.1
      - requests==2.32.3
      - rich==14.2.0
      - rpds-py==0.21.0
      - rsa==4.9
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - s2clientprotocol==5.0.13.92440.3
      - s2protocol==5.0.13.92440.4
      - safetensors==0.7.0
      - scipy==1.12.0
      - seaborn==0.13.2
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - setuptools==75.5.0
      - six==1.16.0
      - sk-video==1.1.10
      - smmap==5.0.1
      - supersuit==3.7.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorflow-probability==0.25.0
      - tensorstore==0.1.78
      - termcolor==2.5.0
      - thop==0.1.1-2209072238
      - tinyscaler==1.2.8
      - tomli==2.1.0
      - toolz==1.1.0
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tqdm==4.67.0
      - treescope==0.1.10
      - trimesh==4.10.1
      - triton==3.0.0
      - tzdata==2025.2
      - urllib3==2.2.3
      - virtualenv==20.27.1
      - wandb==0.18.6
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wheel==0.38.0
variables:
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl
